### PR TITLE
virtual enviroment add in kitsune theme

### PR DESCRIPTION
**Pull request by ankur-gupta-29**
last change does not working.so i do some change in this theme

### CODE REVIEW

**Comment by akinomyoga** [comment]
Ah, OK. `$_omb_prompt_get_python_venv` was the typo of `$python_venv`. However, this PR seems to contain other unrelated changes. Are there any other essential parts needed for the fix?

**Comment by ankur-gupta-29** [comment]
No, i don't found any.

**Comment by ankur-gupta-29** [comment]
I have removed that typo now it is working

**Review by akinomyoga — APPROVED** [review]
Perfect! Thank you!

**Pull request merged**
