### PR TITLE
Add a Codacy badge to README.md

### PR DESCRIPTION
**Pull request by codacy-badger**

### CODE REVIEW

**Comment by Kreyren** [comment]
Do not merge yet

**Comment by nntoan** [comment]
@Kreyren That's the wrong badge from Codacy. This is our current project on Codacy: https://app.codacy.com/app/OhMyBash/oh-my-bash/

**Comment by Kreyren** [comment]
> @Kreyren That's the wrong badge from Codacy. This is our current project on Codacy: https://app.codacy.com/app/OhMyBash/oh-my-bash/

i know this is what codacy generates leaving as do-not-merge untill we decide on updated documents like CONTRIBUTING.md

**Comment by nntoan** [comment]
Closing for now.

**Pull request closed without merging**
