### PR TITLE
Fix: stop SDKMAN! plugin initialisation breaking NVM

### LINKED ISSUE #224: SDKMAN! plugin init messes up NVM installation
greetings.. interestingly, I only discovered this issue when switching my Pop!_OS shell from `bash` to `zsh`.

basically, the current initialisation logic in [`sdkman.plugin.sh`](https://github.com/ohmybash/oh-my-bash/blob/4db7436384e0ddfa62911a101b69dd03a0df53fe/plugins/sdkman/sdkman.plugin.sh) causes NVM to be installed to `$HOME/.sdkman` instead of `$HOME/.nvm`.

after manually fixing this file locally and moving my installed Node versions and aliases to the correct place, everything worked as expected in both Bash and ZSH.

### PR DESCRIPTION
**Pull request by agreeff**
closes #224

### CODE REVIEW

**Comment by agreeff** [comment]
note: I'm closing this PR because I'm ditching this @agreeff account, moving everything over to my personal @ZaLiTHkA account instead.

it seems like this is still an issue in the current SDKMAN release though, so I will sort out a new PR from the appropriate account in the near future.

**Comment by akinomyoga** [comment]
FYI, this was fixed in fd6e34ea2354e8e6f66fd7e800b40aaad1a77570 as per #218.

**Comment by akinomyoga** [comment]
@ZaLiTHkA I have applied the change to the master in commit 1eea954. Thank you!

**Comment by ZaLiTHkA** [comment]
nice timing.. I was just about to say, this old PR of mine did actually have one change that #218 didn't.. (:

**Comment by akinomyoga** [comment]
Oh, OK! Thank you for checking #218!

**Pull request closed without merging**
