### PR TITLE
plugins/cargo: Added a new plugin for working with cargo

### PR DESCRIPTION
**Pull request by leonovk**
Added a plugin for working with cargo, made aliases for cargo itself and also for the most frequently used commands.

### CODE REVIEW

**Review by akinomyoga — APPROVED** [review]

**Comment by leonovk** [comment]
@akinomyoga Hi, what else needs to be done to get the PR into the master? According to the documentation, each new plugin needs to be tested by a tester. How is this process usually organized here?

**Comment by akinomyoga** [comment]
Nothing. I'll later merge this.

**Comment by akinomyoga** [comment]
Thank you!

**Comment by leonovk** [comment]
Thank you too!

**Pull request merged**
