### PR TITLE
completetion/git: Blind fix for #65 due #62

### PR DESCRIPTION
**Pull request by Kreyren**
Warning: Blind fix -> do-not-merge untill tested

Fixes: #65
Fixes: #62

Signed-off-by: Jacob Hrbek <werifgx@gmail.com>

### CODE REVIEW

**Comment by Kreyren** [comment]
sidenote: i don't really like the way that completetion/git is written, but this MR is not made to fix code quality.

**Comment by Kreyren** [comment]
~~btw. 100!~~

**Comment by Kreyren** [comment]
@hashlash Please verify if this fix is sufficient.

**Comment by hashlash** [comment]
It turns out that `--list-cmds` only exists on [`git>=2.18.0`][1], but not on [`git<=2.17.0`][2]

```console
root@c862819b5e7d:/# git --version
git version 2.17.2
root@c862819b5e7d:/# git --list-cmds
unknown option: --list-cmds
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```


  [1]: https://git-scm.com/docs/git/2.18.0#git---list-cmdsgroupgroup82308203
  [2]: https://git-scm.com/docs/git/2.17.0

**Comment by hashlash** [comment]
Btw, how about using `git`'s original completion? So we don't have to worry about handling different versions of git.

https://github.com/git/git/blob/master/contrib/completion/git-completion.bash

**Comment by Kreyren** [comment]
> Btw, how about using `git`'s original completion? So we don't have to worry about handling different versions of git.
> 
> https://github.com/git/git/blob/master/contrib/completion/git-completion.bash

That actually seems to be the same file, but updated lol..

Created commit, please test

**Comment by Kreyren** [comment]
Fixed QA

```
Warning	ShellCheck	hash appears unused. Verify use (or export if used externally). [SC2034]	814:16
Warning	ShellCheck	Remove space after = if trying to assign a value (for empty string, use var='' ... ). [SC1007]	1110:14
Warning	ShellCheck	__git_ref_fieldlist appears unused. Verify use (or export if used externally). [SC2034]	1294:1
Warning	ShellCheck	Remove space after = if trying to assign a value (for empty string, use var='' ... ). [SC1007]	2212:33
Warning	ShellCheck	service is referenced but not assigned. [SC2154]	3118:20
```

Still present

**Comment by Kreyren** [comment]
Code is not compatible in shell -> forcing bash

<details>

```
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	63:27
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	98:23
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	107:2
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	114:9
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	116:9
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	118:8
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	120:4
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	126:10
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	129:10
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	132:10
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	135:10
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	139:11
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	140:11
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	142:10
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	147:6
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	153:12
Warning	ShellCheck	In POSIX sh, string indexing is undefined. [SC2039]	156:12
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	220:2
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	222:11
Warning	ShellCheck	In POSIX sh, arrays are undefined. [SC2039]	225:10
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	225:12
Warning	ShellCheck	In POSIX sh, arithmetic for loops are undefined. [SC2039]	230:2
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	230:42
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	230:47
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	236:10
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	238:7
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	238:7
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	238:42
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	243:5
Warning	ShellCheck	In POSIX sh, -- is undefined. [SC2039]	243:8
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	246:15
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	246:27
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	250:7
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	251:5
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	251:8
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	257:14
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	257:26
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	267:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	273:7
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	280:9
Warning	ShellCheck	In POSIX sh, arrays are undefined. [SC2039]	283:10
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	283:12
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	303:2
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	303:12
Warning	ShellCheck	In POSIX sh, arrays are undefined. [SC2039]	305:12
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	310:2
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	312:6
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	313:15
Warning	ShellCheck	In POSIX sh, arrays are undefined. [SC2039]	320:12
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	333:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	339:3
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	339:19
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	341:7
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	345:7
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	350:16
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	355:3
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	355:19
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	357:7
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	359:8
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	360:17
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	365:7
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	370:16
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	379:4
Warning	ShellCheck	In POSIX sh, 'compgen' is undefined. [SC2039]	382:11
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	397:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	398:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	399:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	401:2
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	401:31
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	402:2
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	408:27
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	411:13
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	423:2
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	423:12
Warning	ShellCheck	In POSIX sh, arrays are undefined. [SC2039]	438:12
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	450:2
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	450:12
Warning	ShellCheck	In POSIX sh, arrays are undefined. [SC2039]	452:12
Warning	ShellCheck	In POSIX sh, 'compgen' is undefined. [SC2039]	456:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	469:2
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	469:12
Warning	ShellCheck	In POSIX sh, 'compgen' is undefined. [SC2039]	479:2
Warning	ShellCheck	In POSIX sh, == in place of = is undefined. [SC2039]	489:12
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	491:36
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	495:30
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	509:2
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	512:19
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	589:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	612:2
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	614:31
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	622:2
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	624:31
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	643:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	644:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	645:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	646:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	647:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	648:2
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	648:17
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	672:6
Warning	ShellCheck	In POSIX sh, arrays are undefined. [SC2039]	681:9
Warning	ShellCheck	In POSIX sh, arrays are undefined. [SC2039]	695:9
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	701:5
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	732:4
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	764:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	785:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	800:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	812:2
Warning	ShellCheck	hash appears unused. Verify use (or export if used externally). [SC2034]	814:16
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	829:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	869:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	931:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	931:25
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	932:2
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	934:3
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	934:6
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	937:6
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	954:3
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	954:6
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1040:2
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	1040:27
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1055:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1080:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	1082:9
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	1089:3
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	1089:6
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1109:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1110:2
Warning	ShellCheck	Remove space after = if trying to assign a value (for empty string, use var='' ... ). [SC1007]	1110:14
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	1117:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	1119:9
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	1127:3
Warning	ShellCheck	In POSIX sh, -- is undefined. [SC2039]	1127:6
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1139:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	1141:16
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	1144:3
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	1144:6
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1160:2
Warning	ShellCheck	In POSIX sh, arithmetic for loops are undefined. [SC2039]	1163:2
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	1163:32
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	1164:9
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	1170:5
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	1175:5
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	1178:5
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	1178:8
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1238:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1272:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1274:2
Warning	ShellCheck	__git_ref_fieldlist appears unused. Verify use (or export if used externally). [SC2034]	1294:1
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1298:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	1301:6
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	1306:3
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	1306:6
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1328:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	1328:13
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1360:3
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	1602:5
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1616:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1754:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1892:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1894:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	1953:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2053:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2055:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2128:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2129:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2184:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2212:2
Warning	ShellCheck	Remove space after = if trying to assign a value (for empty string, use var='' ... ). [SC1007]	2212:33
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	2214:9
Warning	ShellCheck	In POSIX sh, -- is undefined. [SC2039]	2226:8
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2241:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2267:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2277:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2346:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2351:3
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	2353:23
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2357:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2365:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2370:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2375:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2380:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2386:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2394:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2400:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2416:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2421:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2487:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2489:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2616:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2617:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2619:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2680:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2682:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2728:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2735:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2739:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2740:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2748:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2754:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2827:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	2829:6
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	2839:3
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	2839:6
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2869:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2871:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2898:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2923:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2924:2
Warning	ShellCheck	In POSIX sh, string replacement is undefined. [SC2039]	2924:30
Warning	ShellCheck	In POSIX sh, 'declare' is undefined. [SC2039]	2925:7
Warning	ShellCheck	In POSIX sh, 'declare' is undefined. [SC2039]	2926:3
Warning	ShellCheck	In POSIX sh, 'declare' is undefined. [SC2039]	2930:5
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2945:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	2946:2
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	2949:6
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	2952:16
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	2952:19
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	2952:37
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	2955:31
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	2955:34
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	2956:32
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	2957:4
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	2957:7
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	2958:29
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	2958:34
Warning	ShellCheck	In POSIX sh, standalone ((..)) is undefined. [SC2039]	2963:3
Warning	ShellCheck	In POSIX sh, ++ is undefined. [SC2039]	2963:6
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3011:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3022:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3025:2
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	3042:4
Warning	ShellCheck	In POSIX sh, [[ ]] is undefined. [SC2039]	3045:4
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3054:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3060:4
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	3060:16
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3061:4
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3080:3
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	3080:13
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3089:3
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	3089:13
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3098:3
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	3098:13
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3107:3
Warning	ShellCheck	In POSIX sh, $'..' is undefined. [SC2039]	3107:13
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3114:3
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	3115:7
Warning	ShellCheck	In POSIX sh, array references are undefined. [SC2039]	3116:8
Warning	ShellCheck	In POSIX sh, 'let' is undefined. [SC2039]	3117:3
Warning	ShellCheck	service is referenced but not assigned. [SC2154]	3118:20
Warning	ShellCheck	In POSIX sh, 'let' is undefined. [SC2039]	3119:3
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3129:2
Warning	ShellCheck	In POSIX sh, 'local' is undefined. [SC2039]	3139:2
Warning	ShellCheck	In POSIX sh, 'complete' is undefined. [SC2039]	3141:2
Warning	ShellCheck	In POSIX sh, 'complete' is undefined. [SC2039]	3142:6
```

</details>

**Comment by Kreyren** [comment]
`git.completion.sh` is not defined in the project -> No need to adapt compatibility for different naming.

**Comment by Kreyren** [comment]
@hashlash requesting testing

**Comment by hashlash** [comment]
Tried on version 2.17.2 and it doesn't work, while it works on 2.23.0

**Comment by Kreyren** [comment]
Notice: i'm currently busy to investigate this i will fix it with ETA +- 5 days.

**Comment by Kreyren** [comment]
Notice: i'm thinking about fix by making git submodule to fetch this file from upstream and the issue fixes to upstream since this file is expected to be synced.

**Pull request closed without merging**
