### PR TITLE
lib, themes: Preserve users' PROMPT_DIRTRIM

### PR DESCRIPTION
**Pull request by dadreggors**
This change will allow a user to export the PROMPT_DIRTRIM variable in
their .bashrc and change the prompt path length.

### CODE REVIEW

**Comment by dadreggors** [comment]
It seems this change could be used in the roderik them and the shopt lib as well

**Comment by akinomyoga** [comment]
> It seems this change could be used in the roderik them and the shopt lib as well

Thank you for the PR! Could you also include the changes to these themes and libraries?

**Comment by akinomyoga** [comment]
I've rebased it.

**Comment by akinomyoga** [comment]
> > It seems this change could be used in the roderik them and the shopt lib as well
> 
> Thank you for the PR! Could you also include the changes to these themes and libraries?

I have applied the change to also `lib/shopt`, `themes/roderik`, and `themes/vscode`.

**Review by akinomyoga — APPROVED** [review]

**Pull request merged**
