### PR TITLE
I'm Dominicano  README.md

### PR DESCRIPTION
**Pull request by JoseMRT2004**
I added documentation for the Git plugin.

### CODE REVIEW

**Comment by akinomyoga** [comment]
This conflicts with your other PR. Which one is the one to consider?

**Comment by JoseMRT2004** [comment]
"Only the second one, which has more contributions. In the first one, it was just a small test."

**Comment by akinomyoga** [comment]
If you want to modify the content of a PR, please push the commits to the branch of the PR rather than creating another PR.

**Comment by JoseMRT2004** [comment]
Cree otra Branch y realice los cambios solo espero el merge, ya hice otro pull request

**Comment by JoseMRT2004** [comment]
esperando noticias

**Pull request closed without merging**
