### PR TITLE
adding file for agnoster theme

### LINKED ISSUE #59: Problem with agnoster theme.
Making agnoster as default theme, the terminal displays a message saying "No such file of directory" for the file agnoster.theme.sh. When I looked into the directory, their is a file named agnoster-bash.theme.sh

### PR DESCRIPTION
**Pull request by rpotter12**
adding agnoster.theme.sh file
fixes #59

### CODE REVIEW

**Comment by rpotter12** [comment]
@nntoan please review this PR

**Comment by Kreyren** [comment]
Obsolete by https://github.com/ohmybash/oh-my-bash/pull/71

Reasoning: I've updated logic for this scenario instead of making hotfix by making symlinks.

**Comment by rpotter12** [comment]
@Kreyren agnoster theme needs addition file to work properly which is given by this PR. I think this needs to be merged. Please elaborate how #71 solve this issue :)

**Comment by Kreyren** [comment]
> @Kreyren agnoster theme needs addition file to work properly which is given by this PR. I think this needs to be merged. Please elaborate how #71 solve this issue :)

Disclaimer: Using https://github.com/RXT067/what-the-bash

Doubt that it's needed assuming that you are providing duplicate of `agnoster.base.sh` with name `agnoster.theme.sh` and symlink from `agnoster.bash` to `agnoster.bash` ?

Note that `agnoster.bash.sh` works with symlink from `agnoster.theme.sh`

image

**Comment by Kreyren** [comment]
Created https://github.com/ohmybash/oh-my-bash/pull/71/commits/76f7bc9e0fedd2c7a25e3e310cc45859dd55d9cd with proposed fix

**Comment by Kreyren** [comment]
Fixed in #71

**Pull request closed without merging**
